<a href="https://colab.research.google.com/github/caladriusllc-code/caladrius-ml-learn/blob/learning-branch/data_treatment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('/content/DAX - Données Historiques.csv')
data.tail(5)

,Date,Dernier,Ouv.,Plus Haut,Plus Bas,Vol.,Variation %
4995,28/08/2020,"13.033,20","13.140,60","13.147,24","12.951,26","63,77M","-0,48%"
4996,31/08/2020,"12.945,38","13.103,93","13.148,19","12.923,76","59,56M","-0,67%"
4997,01/09/2020,"12.974,25","13.037,20","13.127,28","12.850,30","63,05M","0,22%"
4998,02/09/2020,"13.243,43","13.071,66","13.303,17","13.062,17","80,77M","2,07%"
4999,03/09/2020,"13.057,77","13.354,72","13.460,46","13.004,83","81,70M","-1,40%"

On va créer un dataset qu'on va utiliser pour effectuer des prédictions sur les rendements futures. Sur les deux rendements futurs pour être plus plus précis.

In [4]:
data['Rendement'] = data['Variation %'].str.replace(',', '.').str.replace('%', '').astype(float) / 100
data['Rendement_futur_1'] = data['Rendement'].shift(-1)
data['Rendement_futur_2'] = data['Rendement'].shift(-2)

data['Target'] = ((data['Rendement_futur_1'] > 0) & (data['Rendement_futur_2'] > 0)) | \
                 ((data['Rendement_futur_1'] < 0) & (data['Rendement_futur_2'] < 0))

data['Target'] = data['Target'].astype(int)

data.head()

,Date,Dernier,Ouv.,Plus Haut,Plus Bas,Vol.,Variation %,Rendement,Rendement_futur_1,Rendement_futur_2,Target
0,02/01/2001,"6.289,82","6.431,14","6.439,23","6.289,82",NaN,"-7,26%",-0.0726,0.0231,-0.0091,0
1,03/01/2001,"6.434,96","6.284,87","6.467,82","6.172,44",NaN,"2,31%",0.0231,-0.0091,0.0009,0
2,04/01/2001,"6.376,54","6.443,87","6.556,94","6.356,92",NaN,"-0,91%",-0.0091,0.0009,0.0015,1
3,05/01/2001,"6.382,31","6.383,33","6.485,34","6.344,16",NaN,"0,09%",0.0009,0.0015,0.0019,1
4,08/01/2001,"6.392,17","6.368,83","6.426,64","6.337,95",NaN,"0,15%",0.0015,0.0019,-0.0132,0